# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x65rtus.proto\x12\x06\x63\x65rtus\"7\n\nCertusTime\x12\x13\n\x0bunix_time_s\x18\x01 \x01(\r\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\r\"J\n\tCertusLLA\x12\x14\n\x0clatitude_rad\x18\x01 \x01(\x01\x12\x15\n\rlongitude_rad\x18\x02 \x01(\x01\x12\x10\n\x08height_m\x18\x03 \x01(\x01\"\\\n\x12\x43\x65rtusBodyVelocity\x12\x16\n\x0evelocity_x_mps\x18\x01 \x01(\x02\x12\x16\n\x0evelocity_y_mps\x18\x02 \x01(\x02\x12\x16\n\x0evelocity_z_mps\x18\x03 \x01(\x02\"w\n\x15\x43\x65rtusAngularVelocity\x12\x1e\n\x16\x61ngular_velocity_x_rps\x18\x01 \x01(\x02\x12\x1e\n\x16\x61ngular_velocity_y_rps\x18\x02 \x01(\x02\x12\x1e\n\x16\x61ngular_velocity_z_rps\x18\x03 \x01(\x02\"M\n\x11\x43\x65rtusOrientation\x12\x10\n\x08roll_rad\x18\x01 \x01(\x02\x12\x11\n\tpitch_rad\x18\x02 \x01(\x02\x12\x13\n\x0bheading_rad\x18\x03 \x01(\x02\"[\n\x14\x43\x65rtusPositionStdDev\x12\x14\n\x0clat_stddev_m\x18\x01 \x01(\x02\x12\x14\n\x0clon_stddev_m\x18\x02 \x01(\x02\x12\x17\n\x0fheight_stddev_m\x18\x03 \x01(\x02\"b\n\x11\x43\x65rtusEulerStdDev\x12\x17\n\x0froll_stddev_rad\x18\x01 \x01(\x02\x12\x18\n\x10pitch_stddev_rad\x18\x02 \x01(\x02\x12\x1a\n\x12heading_stddev_rad\x18\x03 \x01(\x02\"X\n\x11\x43\x65rtusSystemState\x12\x15\n\rsystem_status\x18\x01 \x01(\r\x12\x15\n\rfilter_status\x18\x02 \x01(\r\x12\x15\n\rgnss_fix_type\x18\x03 \x01(\r\"*\n\x10\x43\x65rtusSatellites\x12\x16\n\x0enum_satellites\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'certus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CERTUSTIME._serialized_start=24
  _CERTUSTIME._serialized_end=79
  _CERTUSLLA._serialized_start=81
  _CERTUSLLA._serialized_end=155
  _CERTUSBODYVELOCITY._serialized_start=157
  _CERTUSBODYVELOCITY._serialized_end=249
  _CERTUSANGULARVELOCITY._serialized_start=251
  _CERTUSANGULARVELOCITY._serialized_end=370
  _CERTUSORIENTATION._serialized_start=372
  _CERTUSORIENTATION._serialized_end=449
  _CERTUSPOSITIONSTDDEV._serialized_start=451
  _CERTUSPOSITIONSTDDEV._serialized_end=542
  _CERTUSEULERSTDDEV._serialized_start=544
  _CERTUSEULERSTDDEV._serialized_end=642
  _CERTUSSYSTEMSTATE._serialized_start=644
  _CERTUSSYSTEMSTATE._serialized_end=732
  _CERTUSSATELLITES._serialized_start=734
  _CERTUSSATELLITES._serialized_end=776
# @@protoc_insertion_point(module_scope)
